import React, { useState } from "react";
import "./FAQ.css"; // Ensure you create this CSS file

const faqData = [
  {
    question: "What is Capital Gains?",
    answer: "Capital gains are the profits made from selling an asset or investment for more than its purchase price. The gain is the difference between the selling price and the purchase price.",
  },
  {
    question: "What is Capital Loss?",
    answer: "Capital losses occur when an asset or investment is sold for less than its purchase price. The loss is the difference between the selling price and the purchase price.",
  },
  {
    question: "What is revenue?",
    answer: "Revenue is the total amount of money generated by the sale of goods or services before any expenses are subtracted. It represents the top line of a company's income statement and is a measure of the company's financial performance.",
  },
  {
    question: "What is the difference between Capital Gains and Profit Margins?",
    answer: " Both are profits. Capital Gains are calculated as the difference between the selling and purchase price of an investment. Profit margins measure the percentage of revenue that exceeds the costs of production or operations.",
  },
  {
    question: "Is there a return policy for fruits purchased?",
    answer: "You are welcome to sell your fruit back to us at the industry's current rate.",
  },
  {
    question: "What is diversification and how does it apply to the fruit market?",
    answer: "Diversification is an investment strategy that involves spreading investments across various assets to reduce risk. In the fruit market, diversifying means investing in a variety of fruits to minimize the impact of price fluctuations of a single fruit on your overall investment.",
  },
  {
    question: "How does risk management work in the context of fruit investments?",
    answer: "Risk management involves identifying, analyzing, and mitigating potential risks to protect your investments. In the fruit market, risk management might include diversifying your fruit investments, watching for gains and losses, or regularly reviewing market trends to avoid significant losses.",
  },
  {
    question: "What are dividends and how might they be relevant to fruit market investments?",
    answer: "Dividends are payments made to shareholders from a company's profits. While our fruit market currently focuses on buying and selling fruits, if you invest in fruit-related companies, you might receive dividends as a return on your investment.",
  },
  {
    question: "Is it good to buy when the prices are under their median value?",
    answer: "Buying when prices are below their median value can be a good strategy if you believe the prices will rise in the future. It's important to consider market trends and other factors that might affect fruit prices before making a decision.",
  },
];

const FaqPage = () => {
  const [flippedIndex, setFlippedIndex] = useState(null);

  const handleFlip = (index) => {
    setFlippedIndex(flippedIndex === index ? null : index);
  };

  return (
    <div className="faq-container">
      {faqData.map((item, index) => (
        <div
          key={index}
          className={`faq-card ${flippedIndex === index ? "flipped" : ""}`}
          onClick={() => handleFlip(index)}
        >
          <div className="faq-card-inner">
            <div className="faq-card-front">
              <h3>{item.question}</h3>
            </div>
            <div className="faq-card-back">
              <p>{item.answer}</p>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
};

export default FaqPage;
